(function () {
  'use strict';

  angular
      .module('vinibar.winemaker.characteristics', [])
      .factory('WineCharacteristicsFactory', WineCharacteristicsFactory);

  /* @ngInject */
  function WineCharacteristicsFactory () {
    return {
      varieties: [
        "ABONDANT",
        "ABOURIOU (GAMAY SAINT-LAURENT)",
        "ABOURIOU",
        "ALEATICO",
        "ALICANTE BOUSCHET",
        "ALIGOTÉ",
        "ALPHONSE LAVALLÉE",
        "ALTESSE",
        "ALVARINHO",
        "ALÉATICO",
        "ARAGNAN",
        "ARAMON BLANC",
        "ARAMON GRIS",
        "ARAMON",
        "ARANEL",
        "ARBANE",
        "ARGENTÉ",
        "ARINARNOA",
        "ARRILOBA",
        "ARROUYA",
        "ARRUFIAC",
        "ARVINE",
        "AUBIN VERT",
        "AUBIN",
        "AUBUN",
        "AUXERROIS",
        "BACHET",
        "BACO BLANC",
        "BARBAROUX",
        "BAROQUE",
        "BIANCU GENTILE",
        "BLANC DAME",
        "BLANC",
        "BLANQUEIRON",
        "BOUCHALÈS",
        "BOUILLET",
        "BOUQUETTRAUBE",
        "BOURBOULENC",
        "BOUTEILLAN",
        "BRACHET",
        "BRAQUET",
        "BRUN ARGENTÉ",
        "BRUN FOURCA",
        "BRUN",
        "BÉCLAN",
        "BÉQUIGNOL",
        "CABERNET FRANC",
        "CABERNET SAUVIGNON",
        "CABERNET",
        "CALADOC",
        "CALITOR",
        "CAMARALET DE LASSEUBE",
        "CARCAJOLO BLANC",
        "CARCAJOLO",
        "CARDINAL",
        "CARIGNAN BLANC",
        "CARIGNAN",
        "CARMÉNÈRE",
        "CASTETS",
        "CHAMBOURCIN",
        "CHARDONNAY",
        "CHARSAN",
        "CHASAN",
        "CHASSELAS ROSE",
        "CHASSELAS ROSÉ",
        "CHASSELAS",
        "CHATUS",
        "CHENANSON NOIR",
        "CHENANSON",
        "CHENIN",
        "CINSAULT",
        "CINSAUT",
        "CLAIRETTE ROSE",
        "CLAIRETTE",
        "CLARIN",
        "CLAVERIE",
        "CODIVARTA",
        "COLOBEL",
        "COLOMBARD",
        "COLOMBAUD",
        "CORBEAU",
        "COT",
        "COUDERC NOIR",
        "COUDERC",
        "COUNOISE",
        "COURBU NOIR",
        "COURBU",
        "COUSTON",
        "CROUCHEN",
        "CÉSAR",
        "CÔT",
        "DANLAS",
        "DOUCILLON BLANC",
        "DURAS",
        "DURIF",
        "EGIODOLA",
        "EKIGAÏNA",
        "ELBLING",
        "ETRAIRE DE LA DUI",
        "FER SERVADOU",
        "FER",
        "FERRAUDOU",
        "FEUNATE",
        "FLORENTAL",
        "FOLIGNAN",
        "FOLLE BLANCHE",
        "FOURCA",
        "FRANC NOIR DE HAUTE-SAÔNE",
        "FRÉAUX",
        "FUELLA NERA",
        "FURMINT",
        "GAMARET",
        "GAMAY DE BOUZE",
        "GAMAY DE CHAUDENAY",
        "GAMAY FRÉAUX",
        "GAMAY NOIR À JUS BLANC",
        "GAMAY NOIR",
        "GAMAY",
        "GANSON",
        "GARONNET",
        "GASCON",
        "GENOVÈSE",
        "GENTILE",
        "GEWURZTRAMINER",
        "GOLDRIESLING",
        "GOUGET",
        "GRAINS",
        "GRAISSE",
        "GRAMON",
        "GRASSEN",
        "GRENACHE BLANC",
        "GRENACHE GRIS",
        "GRENACHE NOIR",
        "GRENACHE ROUGE",
        "GRENACHE",
        "GRINGET",
        "GROLLEAU GRIS",
        "GROLLEAU",
        "GROS MANSENG",
        "GROS VERT",
        "JACQUÈRE",
        "JOUBERTIN",
        "JURANÇON BLANC",
        "JURANÇON NOIR",
        "KNIPPERLÉ",
        "LANDAL",
        "LAUZET",
        "LEN DE L'EL",
        "LILIORILA",
        "LISTAN",
        "LIVAL",
        "LLEDONER PELUT",
        "LLEDONER PELUT",
        "LLEDONNER PELUT",
        "LÉON MILLOT",
        "MACABEU",
        "MALBEC",
        "MANCIN",
        "MANOSQUIN",
        "MANSENG NOIR",
        "MANSENG",
        "MARSANNE",
        "MARSELAN",
        "MARÉCHAL FOCH ",
        "MARÉCHAL FOCH",
        "MAUZAC BLANC",
        "MAUZAC ROSE",
        "MAUZAC ROSÉ",
        "MAUZAC",
        "MAYORQUIN",
        "MECLE",
        "MELON",
        "MERILLE",
        "MERLOT BLANC",
        "MERLOT NOIR",
        "MERLOT",
        "MESLIER SAINT-FRANÇOIS",
        "MILGRANET",
        "MOLETTE",
        "MOLLARD",
        "MONCADE",
        "MONDEUSE BLANCHE",
        "MONDEUSE",
        "MONERAC",
        "MONTILS",
        "MORNEN",
        "MORRASTEL (MINUSTELLO)",
        "MORRASTEL",
        "MOURVAISON",
        "MOURVÈDRE",
        "MOUYSSAGUÈS",
        "MURESCONU",
        "MUSCADELLE",
        "MUSCADIN",
        "MUSCARDIN",
        "MUSCAT CENDRÉ",
        "MUSCAT D'ALEXANDRIE",
        "MUSCAT DE HAMBOURG",
        "MUSCAT OTTONEL",
        "MUSCAT PETITS GRAINS",
        "MUSCAT À PETITS GRAINS BLANCS",
        "MUSCAT À PETITS GRAINS COTEAUX DE L'AINS",
        "MUSCAT À PETITS GRAINS ROSÉS",
        "MUSCAT À PETITS GRAINS ROUGES",
        "MUSCAT À PETITS GRAINS",
        "MUSCAT À PETITS GRAINS",
        "MÈCLE",
        "MÉRILLE",
        "MÜLLER-THURGAU",
        "NIELLUCIO",
        "NOIR FLEURIEN",
        "NÉGRET DE BANHARS",
        "NÉGRETTE",
        "OBERLIN",
        "ONDENC",
        "ORBOIS",
        "PAGADEBITI",
        "PANSE MUSCADE (OU PANSE DU ROY RENÉ)",
        "PARELLADA",
        "PASCAL",
        "PERDEA",
        "PERSAN",
        "PETIT BRUN",
        "PETIT COURBU",
        "PETIT MANSENG",
        "PETIT MESLIER",
        "PETIT VERDOT N",
        "PETIT VERDOT",
        "PICARDAN",
        "PINEAU D'AUNIS",
        "PINEAU DE LA LOIRE",
        "PINOT BLANC",
        "PINOT GRIS",
        "PINOT MEUNIER",
        "PINOT NOIR VINIFÉ EN BLANC",
        "PINOT NOIR",
        "PINOT",
        "PIQUEPOUL BLANC",
        "PIQUEPOUL GRIS",
        "PIQUEPOUL NOIR",
        "PIQUEPOUL",
        "PLANT DE BRUNEL",
        "PLANT DROIT",
        "PLANTET",
        "PORTAN",
        "PORTUGAIS BLEU",
        "POULSARD",
        "PRUNELARD",
        "PRÉCOCE BOUSQUET",
        "PRÉCOCE DE MALINGRE",
        "RAFFIAT DE MONCADE",
        "RAVAT BLANC",
        "RAYON D'OR",
        "RIBOL",
        "RIESLING",
        "RIMINÈSE",
        "RIVAIRENC BLANC",
        "RIVAIRENC GRIS",
        "RIVAIRENC",
        "ROLLE",
        "ROMORANTIN",
        "ROSÉ DU VAR",
        "ROUBLOT",
        "ROUSSANNE",
        "ROUSSETTE D'AYZE",
        "RUBILANDE",
        "SACY",
        "SAINT-CÔME",
        "SAINT-MACAIRE",
        "SAINT-PIERRE DORÉ",
        "SAUVIGNON BLANC",
        "SAUVIGNON GRIS",
        "SAUVIGNON",
        "SAVAGNIN BLANC",
        "SAVAGNIN ROSE",
        "SAVAGNIN ROSÉ (TRAMINER)",
        "SAVAGNIN",
        "SCIACCARELLO",
        "SEINOIR",
        "SELECT",
        "SERVANIN",
        "SERVANT",
        "SEYVAL",
        "SYLVANER",
        "SYRAH",
        "SÉGALIN",
        "SÉMILLON",
        "SÉMÉBAT",
        "TANANT",
        "TANNAT",
        "TEMPRANILLO",
        "TERRET BLANC",
        "TERRET GRIS",
        "TERRET NOIR",
        "TIBOUREN",
        "TOURBAT (OU MALVOISIE DU ROUSSILLON)",
        "TOURBAT",
        "TRESSALIER",
        "TRESSOT",
        "TROUSSEAU",
        "TÉOULIER",
        "UGNI BLANC (ROUSSAN)",
        "UGNI BLANC",
        "UGNI ROSÉ",
        "UGNI ROSÉ",
        "VALDIGUIÉ",
        "VALDIQUIÉ",
        "VALÉRIEN",
        "VAROUSSET",
        "VELTELINER ROUGE PRÉCOCE",
        "VERDELHO",
        "VERDESSE",
        "VERDOT",
        "VERMENTINO OU ROLLE",
        "VILLARD BLANC",
        "VILLARD NOIR",
        "VILLARD",
        "VIOGNIER"
      ],
      regions: [
        'Alsace',
        'Bordeaux',
        'Beaujolais',
        'Bourgogne',
        'Champagne',
        'Provence',
        'Corse',
        'Jura',
        'Languedoc-Roussillon',
        'Lorraine',
        'Loire',
        'Rhône',
        'Savoie-Bugey',
        'Sud-Ouest'
      ],
      appellations: [
        "Agenais",
        "Ajaccio",
        "Aloxe-Corton",
        "Alpes-de-Haute-Provence",
        "Alpes-Maritimes",
        "Alpilles",
        "Alsace grand cru",
        "Alsace",
        "Anjou",
        "Anjou Villages",
        "Anjou Villages Brissac",
        "Anjou-Coteaux de la Loire",
        "Arbois",
        "Ardèche",
        "Ariège",
        "Atlantique",
        "Aude",
        "Auxey-Duresses",
        "Aveyron",
        "Bandol",
        "Banyuls",
        "Banyuls grand cru",
        "Barsac",
        "Bâtard-Montrachet",
        "Béarn",
        "Beaujolais",
        "Beaujolais Villages",
        "Beaumes de Venise",
        "Beaune",
        "Bellet",
        "Bergerac",
        "Bienvenues-Bâtard-Montrachet",
        "Blagny",
        "Blaye",
        "Bonnes-Mares",
        "Bonnezeaux",
        "Bordeaux",
        "Bordeaux supérieur",
        "Bouches-du-Rhône",
        "Bourgogne",
        "Bourgogne aligoté",
        "Bourgogne mousseux",
        "Bourgogne Passe-tout-grains",
        "Bourgueil",
        "Bouzeron",
        "Brouilly",
        "Brulhois",
        "Bugey",
        "Buzet",
        "Cabardès",
        "Cabernet de Saumur",
        "Cabernet d'Anjou",
        "Cadillac",
        "Cahors",
        "Calvados",
        "Canon Fronsac",
        "Cassis",
        "Cérons",
        "Cévennes",
        "Chablis",
        "Chablis Grand Cru",
        "Chambertin",
        "Chambertin-Clos de Bèze",
        "Chambolle-Musigny",
        "Champagne",
        "Chapelle-Chambertin",
        "Charentais",
        "Charlemagne",
        "Charmes-Chambertin",
        "Chassagne-Montrachet",
        "Château-Chalon",
        "Château-Grillet",
        "Châteaumeillant",
        "Châteauneuf-du-Pape",
        "Châtillon-en-Diois",
        "Chénas",
        "Chevalier-Montrachet",
        "Cheverny",
        "Chinon",
        "Chiroubles",
        "Chorey-lès-Beaune",
        "Cité de Carcassonne",
        "Clairette de Bellegarde",
        "Clairette de Die",
        "Clairette du Languedoc",
        "Clos de la Roche",
        "Clos de Tart",
        "Clos de Vougeot",
        "Clos des Lambrays",
        "Clos Saint-Denis",
        "Collines Rhodaniennes",
        "Collioure",
        "Comté Tolosan",
        "Comtés Rhodaniens",
        "Condrieu",
        "Corbières",
        "Corbières-Boutenac",
        "Cornas",
        "Corton",
        "Corton-Charlemagne",
        "Costières de Nîmes",
        "Côte de Beaune",
        "Côte de Beaune-Villages",
        "Côte de Brouilly",
        "Côte de Nuits-Villages",
        "Côte roannaise",
        "Côte Rôtie",
        "Côte Vermeille",
        "Coteaux Bourguignons",
        "Coteaux champenois",
        "Coteaux d'Aix-en-Provence",
        "Coteaux d'Ensérune",
        "Coteaux de Coiffy",
        "Coteaux de Die",
        "Coteaux de Glanes",
        "Coteaux de l'Ain",
        "Coteaux de l'Auxois",
        "Coteaux de l'Aubance",
        "Coteaux de Narbonne",
        "Coteaux de Peyriac",
        "Coteaux de Saumur",
        "Coteaux de Tannay",
        "Coteaux des Baronnies",
        "Coteaux du Cher et de l'Arnon",
        "Coteaux du Giennois",
        "Coteaux du Layon",
        "Coteaux du Libron",
        "Coteaux du Loir",
        "Coteaux du Lyonnais",
        "Coteaux du Pont du Gard",
        "Coteaux du Quercy",
        "Coteaux du Vendômois",
        "Coteaux d'Ancenis",
        "Coteaux varois en Provence",
        "Côtes Catalanes",
        "Côtes d'Auvergne",
        "Côtes de Bergerac",
        "Côtes de Blaye",
        "Côtes de Bordeaux",
        "Côtes de Bordeaux-Saint-Macaire",
        "Côtes de Bourg",
        "Côtes de Duras",
        "Côtes de Gascogne",
        "Côtes de la Charité",
        "Côtes de Meuse",
        "Côtes de Millau",
        "Côtes de Montravel",
        "Côtes de Provence",
        "Côtes de Thau",
        "Côtes de Thongue",
        "Côtes de Toul",
        "Côtes du Forez",
        "Côtes du Jura",
        "Côtes du Lot",
        "Côtes du Marmandais",
        "Côtes du Rhône",
        "Côtes du Rhône Villages",
        "Côtes du Roussillon",
        "Côtes du Roussillon Villages",
        "Côtes du Tarn",
        "Côtes du Vivarais",
        "Cour-Cheverny",
        "Crémant de Bordeaux",
        "Crémant de Bourgogne",
        "Crémant de Die",
        "Crémant de Limoux",
        "Crémant de Loire",
        "Crémant du Jura",
        "Crémant d'Alsace",
        "Criots-Bâtard-Montrachet",
        "Crozes-Hermitage",
        "Drôme",
        "Duché d'Uzès",
        "Echezeaux",
        "Entraygues-Le Fel",
        "Entre-deux-Mers",
        "Estaing",
        "Faugères",
        "Fiefs Vendéens",
        "Fitou",
        "Fixin",
        "Fleurie",
        "Floc de Gascogne",
        "Franche-Comté",
        "Fronsac",
        "Fronton",
        "Gaillac",
        "Gaillac premières côtes",
        "Gard",
        "Gers",
        "Gevrey-Chambertin",
        "Gigondas",
        "Givry",
        "Grand Roussillon",
        "Grands-Echezeaux",
        "Graves",
        "Graves de Vayres",
        "Graves supérieures",
        "Grignan-les-Adhémar",
        "Griotte-Chambertin",
        "Gros Plant du Pays Nantais",
        "Haut-Médoc",
        "Haut-Montravel",
        "Haut-Poitou",
        "Haute Vallée de l'Aude",
        "Haute Vallée de l'Orb",
        "Haute-Marne",
        "Haute-Vienne",
        "Hautes-Alpes",
        "Hermitage",
        "Ile de Beauté",
        "Irancy",
        "Irouléguy",
        "Isère",
        "Jasnières",
        "Juliénas",
        "Jurançon",
        "La Grande Rue",
        "La Romanée",
        "La Tâche",
        "Ladoix",
        "Lalande-de-Pomerol",
        "Landes",
        "Languedoc",
        "Latricières-Chambertin",
        "Lavilledieu",
        "Le Pays Cathare",
        "Les Baux de Provence",
        "Limoux",
        "Lirac",
        "Listrac-Médoc",
        "Loupiac",
        "Luberon",
        "Lussac-Saint-Emilion",
        "L'Etoile",
        "Mâcon",
        "Macvin du Jura",
        "Madiran",
        "Malepère",
        "Maranges",
        "Marcillac",
        "Margaux",
        "Marsannay",
        "Maures",
        "Maury",
        "Mazis-Chambertin",
        "Mazoyères-Chambertin",
        "Méditerranée",
        "Médoc",
        "Menetou-Salon",
        "Mercurey",
        "Meursault",
        "Minervois",
        "Minervois-La Livinière",
        "Monbazillac",
        "Mont Caume",
        "Montagne-Saint-Emilion",
        "Montagny",
        "Monthélie",
        "Montlouis-sur-Loire",
        "Montrachet",
        "Montravel",
        "Morey-Saint-Denis",
        "Morgon",
        "Moselle",
        "Moulin-à-Vent",
        "Moulis",
        "Muscadet",
        "Muscadet Coteaux de la Loire",
        "Muscadet Côtes de Grandlieu",
        "Muscadet Sèvre et Maine",
        "Muscat de Beaumes-de-Venise",
        "Muscat de Frontignan",
        "Muscat de Lunel",
        "Muscat de Mireval",
        "Muscat de Rivesaltes",
        "Muscat de Saint-Jean-de-Minervois",
        "Muscat du Cap Corse",
        "Musigny",
        "Nuits-Saint-Georges",
        "Orléans",
        "Orléans-Cléry",
        "Pacherenc du Vic-Bilh",
        "Palette",
        "Patrimonio",
        "Pauillac",
        "Pays d'Hérault",
        "Pays d'Oc",
        "Pécharmant",
        "Périgord",
        "Pernand-Vergelesses",
        "Pessac-Léognan",
        "Petit Chablis",
        "Pierrevert",
        "Pineau des Charentes",
        "Pomerol",
        "Pommard",
        "Pouilly-Fuissé",
        "Pouilly-Fumé",
        "Pouilly-Loché",
        "Pouilly-sur-Loire",
        "Pouilly-Vinzelles",
        "Premières Côtes de Bordeaux",
        "Puisseguin-Saint-Emilion",
        "Puligny-Montrachet",
        "Puy-de-Dôme",
        "Quarts de Chaume",
        "Quincy",
        "Rasteau",
        "Régnié",
        "Reuilly",
        "Richebourg",
        "Rivesaltes",
        "Romanée-Conti",
        "Romanée-Saint-Vivant",
        "Rosé de Loire",
        "Rosé des Riceys",
        "Rosé d'Anjou",
        "Rosette",
        "Roussette de Savoie",
        "Roussette du Bugey",
        "Ruchottes-Chambertin",
        "Rully",
        "Sable de Camargue",
        "Saint-Amour",
        "Saint-Aubin",
        "Saint-Bris",
        "Saint-Chinian",
        "Saint-Emilion",
        "Saint-Emilion grand cru",
        "Saint-Estèphe",
        "Saint-Georges-Saint-Emilion",
        "Saint-Guilhem-le-Désert",
        "Saint-Joseph",
        "Saint-Julien",
        "Saint-Mont",
        "Saint-Nicolas-de-Bourgueil",
        "Saint-Péray",
        "Saint-Pourçain",
        "Saint-Romain",
        "Saint-Sardos",
        "Saint-Véran",
        "Sainte-Croix-du-Mont",
        "Sainte-Foy-Bordeaux",
        "Sainte-Marie-la-Blanche",
        "Sancerre",
        "Santenay",
        "Saône-et-Loire",
        "Saumur",
        "Saumur-Champigny",
        "Saussignac",
        "Sauternes",
        "Savennières",
        "Savigny-lès-Beaune",
        "Seyssel",
        "Tavel",
        "Thézac-Perricard",
        "Touraine",
        "Touraine Noble Joué",
        "Tursan",
        "Urfé",
        "Vacqueyras",
        "Val de Loire",
        "Valençay",
        "Vallée du Paradis",
        "Vallée du Torgan",
        "Var",
        "Vaucluse",
        "Ventoux",
        "Vicomté d'Aumelas",
        "Vin de Corse",
        "Vin de Savoie",
        "Vin des Allobroges",
        "Vins de la Corrèze",
        "Vinsobres",
        "Viré-Clessé",
        "Volnay",
        "Vosne-Romanée",
        "Vougeot",
        "Vouvray",
        "Yonne",
        "Vin d'Alsace",
        "Vin de Bellet",
        "Clos Vougeot",
        "Bourgogne grand ordinaire",
        "Bourgogne ordinaire",
        "Crozes-Ermitage",
        "Ermitage",
        "l'Hermitage",
        "l'Ermitage",
        "Moulis-en-Médoc",
        "Frontignan",
        "Vin de Frontignan",
        "Pineau Charentais",
        "Blanc Fumé de Pouilly",
        "Corse",
        "Savoie",
        "Côtes du Brian",
        "Neac",
        "Vin de France",
        "Vin de Table",
        "Santenay 1er cru",
        "Chablis 1er cru",
        "Beaune 1er cru",
        "Blagny 1er cru",
        "Auxey-Duresses 1er cru",
        "Aloxe-Corton 1er cru",
        "Maranges 1er cru",
        "Mercurey 1er cru",
        "Meursault 1er cru",
        "Montagny 1er cru",
        "Monthélie 1er cru",
        "Morey-Saint-Denis 1er cru",
        "Nuits-Saint-Georges 1er cru",
        "Pernand-Vergelesses 1er cru",
        "Pommard 1er cru",
        "Volnay 1er cru",
        "Puligny-Montrachet 1er cru",
        "Rully 1er cru",
        "Saint-Aubin 1er cru",
        "Savigny-lès-Beaune 1er cru",
        "Vosne-Romanée 1er cru",
        "Vougeot 1er cru",
        "Chambolle-Musigny 1er cru",
        "Chassagne-Montrachet 1er cru",
        "Fixin 1er cru",
        "Gevrey-Chambertin 1er cru",
        "Givry 1er cru",
        "Ladoix 1er cru",
        "Mâcon-Pierreclos",
        "Terre de Camargue",
        "Maury sec",
        "Saumur-Puy-Notre-Dame",
        "Blaye Côtes de Bordeaux",
        "Coteaux de Béziers",
        "Mont Baudile",
        "Champagne Grand Cru",
        "Saint-Guilhem-le-Désert Cité d'Aniane",
        "Saint-Guilhem-le-Désert Val de Montferrand",
        "Coteaux du Languedoc",
        "Picpoul de Pinet"
      ]
    };
  }
})();