(function () {
  'use strict';

  angular
      .module('vinibar.winemaker.characteristics', [])
      .factory('WineCharacteristicsFactory', WineCharacteristicsFactory);

  /* @ngInject */
  function WineCharacteristicsFactory () {
    return {
      varieties: [
        "ABONDANT",
        "ABOURIOU (GAMAY SAINT-LAURENT)",
        "ABOURIOU",
        "ALEATICO",
        "ALICANTE BOUSCHET",
        "ALIGOTÉ",
        "ALPHONSE LAVALLÉE",
        "ALTESSE",
        "ALVARINHO",
        "ALÉATICO",
        "ARAGNAN",
        "ARAMON BLANC",
        "ARAMON GRIS",
        "ARAMON",
        "ARANEL",
        "ARBANE",
        "ARGENTÉ",
        "ARINARNOA",
        "ARRILOBA",
        "ARROUYA",
        "ARRUFIAC",
        "ARVINE",
        "AUBIN VERT",
        "AUBIN",
        "AUBUN",
        "AUXERROIS",
        "BACHET",
        "BACO BLANC",
        "BARBAROUX",
        "BAROQUE",
        "BIANCU GENTILE",
        "BLANC DAME",
        "BLANC",
        "BLANQUEIRON",
        "BOUCHALÈS",
        "BOUILLET",
        "BOUQUETTRAUBE",
        "BOURBOULENC",
        "BOUTEILLAN",
        "BRACHET",
        "BRAQUET",
        "BRUN ARGENTÉ",
        "BRUN FOURCA",
        "BRUN",
        "BÉCLAN",
        "BÉQUIGNOL",
        "CABERNET FRANC",
        "CABERNET SAUVIGNON",
        "CABERNET",
        "CALADOC",
        "CALITOR",
        "CAMARALET DE LASSEUBE",
        "CARCAJOLO BLANC",
        "CARCAJOLO",
        "CARDINAL",
        "CARIGNAN BLANC",
        "CARIGNAN",
        "CARMÉNÈRE",
        "CASTETS",
        "CHAMBOURCIN",
        "CHARDONNAY",
        "CHARSAN",
        "CHASAN",
        "CHASSELAS ROSE",
        "CHASSELAS ROSÉ",
        "CHASSELAS",
        "CHATUS",
        "CHENANSON NOIR",
        "CHENANSON",
        "CHENIN",
        "CINSAULT",
        "CINSAUT",
        "CLAIRETTE ROSE",
        "CLAIRETTE",
        "CLARIN",
        "CLAVERIE",
        "CODIVARTA",
        "COLOBEL",
        "COLOMBARD",
        "COLOMBAUD",
        "CORBEAU",
        "COT",
        "COUDERC NOIR",
        "COUDERC",
        "COUNOISE",
        "COURBU NOIR",
        "COURBU",
        "COUSTON",
        "CROUCHEN",
        "CÉSAR",
        "CÔT",
        "DANLAS",
        "DOUCILLON BLANC",
        "DURAS",
        "DURIF",
        "EGIODOLA",
        "EKIGAÏNA",
        "ELBLING",
        "ETRAIRE DE LA DUI",
        "FER SERVADOU",
        "FER",
        "FERRAUDOU",
        "FEUNATE",
        "FLORENTAL",
        "FOLIGNAN",
        "FOLLE BLANCHE",
        "FOURCA",
        "FRANC NOIR DE HAUTE-SAÔNE",
        "FRÉAUX",
        "FUELLA NERA",
        "FURMINT",
        "GAMARET",
        "GAMAY DE BOUZE",
        "GAMAY DE CHAUDENAY",
        "GAMAY FRÉAUX",
        "GAMAY NOIR À JUS BLANC",
        "GAMAY NOIR",
        "GAMAY",
        "GANSON",
        "GARONNET",
        "GASCON",
        "GENOVÈSE",
        "GENTILE",
        "GEWURZTRAMINER",
        "GOLDRIESLING",
        "GOUGET",
        "GRAINS",
        "GRAISSE",
        "GRAMON",
        "GRASSEN",
        "GRENACHE BLANC",
        "GRENACHE GRIS",
        "GRENACHE NOIR",
        "GRENACHE ROUGE",
        "GRENACHE",
        "GRINGET",
        "GROLLEAU GRIS",
        "GROLLEAU",
        "GROS MANSENG",
        "GROS VERT",
        "JACQUÈRE",
        "JOUBERTIN",
        "JURANÇON BLANC",
        "JURANÇON NOIR",
        "KNIPPERLÉ",
        "LANDAL",
        "LAUZET",
        "LEN DE L'EL",
        "LILIORILA",
        "LISTAN",
        "LIVAL",
        "LLEDONER PELUT",
        "LLEDONER PELUT",
        "LLEDONNER PELUT",
        "LÉON MILLOT",
        "MACABEU",
        "MALBEC",
        "MANCIN",
        "MANOSQUIN",
        "MANSENG NOIR",
        "MANSENG",
        "MARSANNE",
        "MARSELAN",
        "MARÉCHAL FOCH ",
        "MARÉCHAL FOCH",
        "MAUZAC BLANC",
        "MAUZAC ROSE",
        "MAUZAC ROSÉ",
        "MAUZAC",
        "MAYORQUIN",
        "MECLE",
        "MELON",
        "MERILLE",
        "MERLOT BLANC",
        "MERLOT NOIR",
        "MERLOT",
        "MESLIER SAINT-FRANÇOIS",
        "MILGRANET",
        "MOLETTE",
        "MOLLARD",
        "MONCADE",
        "MONDEUSE BLANCHE",
        "MONDEUSE",
        "MONERAC",
        "MONTILS",
        "MORNEN",
        "MORRASTEL (MINUSTELLO)",
        "MORRASTEL",
        "MOURVAISON",
        "MOURVÈDRE",
        "MOUYSSAGUÈS",
        "MURESCONU",
        "MUSCADELLE",
        "MUSCADIN",
        "MUSCARDIN",
        "MUSCAT CENDRÉ",
        "MUSCAT D'ALEXANDRIE",
        "MUSCAT DE HAMBOURG",
        "MUSCAT OTTONEL",
        "MUSCAT PETITS GRAINS",
        "MUSCAT À PETITS GRAINS BLANCS",
        "MUSCAT À PETITS GRAINS COTEAUX DE L'AINS",
        "MUSCAT À PETITS GRAINS ROSÉS",
        "MUSCAT À PETITS GRAINS ROUGES",
        "MUSCAT À PETITS GRAINS",
        "MUSCAT À PETITS GRAINS",
        "MÈCLE",
        "MÉRILLE",
        "MÜLLER-THURGAU",
        "NIELLUCIO",
        "NOIR FLEURIEN",
        "NÉGRET DE BANHARS",
        "NÉGRETTE",
        "OBERLIN",
        "ONDENC",
        "ORBOIS",
        "PAGADEBITI",
        "PANSE MUSCADE (OU PANSE DU ROY RENÉ)",
        "PARELLADA",
        "PASCAL",
        "PERDEA",
        "PERSAN",
        "PETIT BRUN",
        "PETIT COURBU",
        "PETIT MANSENG",
        "PETIT MESLIER",
        "PETIT VERDOT N",
        "PETIT VERDOT",
        "PICARDAN",
        "PINEAU D'AUNIS",
        "PINEAU DE LA LOIRE",
        "PINOT BLANC",
        "PINOT GRIS",
        "PINOT MEUNIER",
        "PINOT NOIR VINIFÉ EN BLANC",
        "PINOT NOIR",
        "PINOT",
        "PIQUEPOUL BLANC",
        "PIQUEPOUL GRIS",
        "PIQUEPOUL NOIR",
        "PIQUEPOUL",
        "PLANT DE BRUNEL",
        "PLANT DROIT",
        "PLANTET",
        "PORTAN",
        "PORTUGAIS BLEU",
        "POULSARD",
        "PRUNELARD",
        "PRÉCOCE BOUSQUET",
        "PRÉCOCE DE MALINGRE",
        "RAFFIAT DE MONCADE",
        "RAVAT BLANC",
        "RAYON D'OR",
        "RIBOL",
        "RIESLING",
        "RIMINÈSE",
        "RIVAIRENC BLANC",
        "RIVAIRENC GRIS",
        "RIVAIRENC",
        "ROLLE",
        "ROMORANTIN",
        "ROSÉ DU VAR",
        "ROUBLOT",
        "ROUSSANNE",
        "ROUSSETTE D'AYZE",
        "RUBILANDE",
        "SACY",
        "SAINT-CÔME",
        "SAINT-MACAIRE",
        "SAINT-PIERRE DORÉ",
        "SAUVIGNON BLANC",
        "SAUVIGNON GRIS",
        "SAUVIGNON",
        "SAVAGNIN BLANC",
        "SAVAGNIN ROSE",
        "SAVAGNIN ROSÉ (TRAMINER)",
        "SAVAGNIN",
        "SCIACCARELLO",
        "SEINOIR",
        "SELECT",
        "SERVANIN",
        "SERVANT",
        "SEYVAL",
        "SYLVANER",
        "SYRAH",
        "SÉGALIN",
        "SÉMILLON",
        "SÉMÉBAT",
        "TANANT",
        "TANNAT",
        "TEMPRANILLO",
        "TERRET BLANC",
        "TERRET GRIS",
        "TERRET NOIR",
        "TIBOUREN",
        "TOURBAT (OU MALVOISIE DU ROUSSILLON)",
        "TOURBAT",
        "TRESSALIER",
        "TRESSOT",
        "TROUSSEAU",
        "TÉOULIER",
        "UGNI BLANC (ROUSSAN)",
        "UGNI BLANC",
        "UGNI ROSÉ",
        "UGNI ROSÉ",
        "VALDIGUIÉ",
        "VALDIQUIÉ",
        "VALÉRIEN",
        "VAROUSSET",
        "VELTELINER ROUGE PRÉCOCE",
        "VERDELHO",
        "VERDESSE",
        "VERDOT",
        "VERMENTINO OU ROLLE",
        "VILLARD BLANC",
        "VILLARD NOIR",
        "VILLARD",
        "VIOGNIER"
      ],
      regions: [
        'Alsace',
        'Bordeaux',
        'Beaujolais',
        'Bourgogne',
        'Champagne',
        'Provence',
        'Corse',
        'Jura',
        'Languedoc-Roussillon',
        'Lorraine',
        'Loire',
        'Rhône',
        'Savoie-Bugey',
        'Sud-Ouest'
      ],
      appellations: [
        "Agenais",
        "Ajaccio",
        "Aloxe-Corton",
        "Alpes-de-Haute-Provence",
        "Alpes-Maritimes",
        "Alpilles",
        "Alsace grand cru",
        "Alsace",
        "Anjou",
        "Anjou Villages",
        "Anjou Villages Brissac",
        "Anjou-Coteaux de la Loire",
        "Arbois",
        "Ardèche",
        "Ariège",
        "Atlantique",
        "Aude",
        "Auxey-Duresses",
        "Aveyron",
        "Bandol",
        "Banyuls",
        "Banyuls grand cru",
        "Barsac",
        "Bâtard-Montrachet",
        "Béarn",
        "Beaujolais",
        "Beaujolais Villages",
        "Beaumes de Venise",
        "Beaune",
        "Bellet",
        "Bergerac",
        "Bienvenues-Bâtard-Montrachet",
        "Blagny",
        "Blaye",
        "Bonnes-Mares",
        "Bonnezeaux",
        "Bordeaux",
        "Bordeaux supérieur",
        "Bouches-du-Rhône",
        "Bourgogne",
        "Bourgogne aligoté",
        "Bourgogne mousseux",
        "Bourgogne Passe-tout-grains",
        "Bourgueil",
        "Bouzeron",
        "Brouilly",
        "Brulhois",
        "Bugey",
        "Buzet",
        "Cabardès",
        "Cabernet de Saumur",
        "Cabernet d'Anjou",
        "Cadillac",
        "Cahors",
        "Calvados",
        "Canon Fronsac",
        "Cassis",
        "Cérons",
        "Cévennes",
        "Chablis",
        "Chablis Grand Cru",
        "Chambertin",
        "Chambertin-Clos de Bèze",
        "Chambolle-Musigny",
        "Champagne",
        "Chapelle-Chambertin",
        "Charentais",
        "Charlemagne",
        "Charmes-Chambertin",
        "Chassagne-Montrachet",
        "Château-Chalon",
        "Château-Grillet",
        "Châteaumeillant",
        "Châteauneuf-du-Pape",
        "Châtillon-en-Diois",
        "Chénas",
        "Chevalier-Montrachet",
        "Cheverny",
        "Chinon",
        "Chiroubles",
        "Chorey-lès-Beaune",
        "Cité de Carcassonne",
        "Clairette de Bellegarde",
        "Clairette de Die",
        "Clairette du Languedoc",
        "Clos de la Roche",
        "Clos de Tart",
        "Clos de Vougeot",
        "Clos des Lambrays",
        "Clos Saint-Denis",
        "Collines Rhodaniennes",
        "Collioure",
        "Comté Tolosan",
        "Comtés Rhodaniens",
        "Condrieu",
        "Corbières",
        "Corbières-Boutenac",
        "Cornas",
        "Corton",
        "Corton-Charlemagne",
        "Costières de Nîmes",
        "Côte de Beaune",
        "Côte de Beaune-Villages",
        "Côte de Brouilly",
        "Côte de Nuits-Villages",
        "Côte roannaise",
        "Côte Rôtie",
        "Côte Vermeille",
        "Coteaux Bourguignons",
        "Coteaux champenois",
        "Coteaux d'Aix-en-Provence",
        "Coteaux d'Ensérune",
        "Coteaux de Coiffy",
        "Coteaux de Die",
        "Coteaux de Glanes",
        "Coteaux de l'Ain",
        "Coteaux de l'Auxois",
        "Coteaux de l'Aubance",
        "Coteaux de Narbonne",
        "Coteaux de Peyriac",
        "Coteaux de Saumur",
        "Coteaux de Tannay",
        "Coteaux des Baronnies",
        "Coteaux du Cher et de l'Arnon",
        "Coteaux du Giennois",
        "Coteaux du Layon",
        "Coteaux du Libron",
        "Coteaux du Loir",
        "Coteaux du Lyonnais",
        "Coteaux du Pont du Gard",
        "Coteaux du Quercy",
        "Coteaux du Vendômois",
        "Coteaux d'Ancenis",
        "Coteaux varois en Provence",
        "Côtes Catalanes",
        "Côtes d'Auvergne",
        "Côtes de Bergerac",
        "Côtes de Blaye",
        "Côtes de Bordeaux",
        "Côtes de Bordeaux-Saint-Macaire",
        "Côtes de Bourg",
        "Côtes de Duras",
        "Côtes de Gascogne",
        "Côtes de la Charité",
        "Côtes de Meuse",
        "Côtes de Millau",
        "Côtes de Montravel",
        "Côtes de Provence",
        "Côtes de Thau",
        "Côtes de Thongue",
        "Côtes de Toul",
        "Côtes du Forez",
        "Côtes du Jura",
        "Côtes du Lot",
        "Côtes du Marmandais",
        "Côtes du Rhône",
        "Côtes du Rhône Villages",
        "Côtes du Roussillon",
        "Côtes du Roussillon Villages",
        "Côtes du Tarn",
        "Côtes du Vivarais",
        "Cour-Cheverny",
        "Crémant de Bordeaux",
        "Crémant de Bourgogne",
        "Crémant de Die",
        "Crémant de Limoux",
        "Crémant de Loire",
        "Crémant du Jura",
        "Crémant d'Alsace",
        "Criots-Bâtard-Montrachet",
        "Crozes-Hermitage",
        "Drôme",
        "Duché d'Uzès",
        "Echezeaux",
        "Entraygues-Le Fel",
        "Entre-deux-Mers",
        "Estaing",
        "Faugères",
        "Fiefs Vendéens",
        "Fitou",
        "Fixin",
        "Fleurie",
        "Floc de Gascogne",
        "Franche-Comté",
        "Fronsac",
        "Fronton",
        "Gaillac",
        "Gaillac premières côtes",
        "Gard",
        "Gers",
        "Gevrey-Chambertin",
        "Gigondas",
        "Givry",
        "Grand Roussillon",
        "Grands-Echezeaux",
        "Graves",
        "Graves de Vayres",
        "Graves supérieures",
        "Grignan-les-Adhémar",
        "Griotte-Chambertin",
        "Gros Plant du Pays Nantais",
        "Haut-Médoc",
        "Haut-Montravel",
        "Haut-Poitou",
        "Haute Vallée de l'Aude",
        "Haute Vallée de l'Orb",
        "Haute-Marne",
        "Haute-Vienne",
        "Hautes-Alpes",
        "Hermitage",
        "Ile de Beauté",
        "Irancy",
        "Irouléguy",
        "Isère",
        "Jasnières",
        "Juliénas",
        "Jurançon",
        "La Grande Rue",
        "La Romanée",
        "La Tâche",
        "Ladoix",
        "Lalande-de-Pomerol",
        "Landes",
        "Languedoc",
        "Latricières-Chambertin",
        "Lavilledieu",
        "Le Pays Cathare",
        "Les Baux de Provence",
        "Limoux",
        "Lirac",
        "Listrac-Médoc",
        "Loupiac",
        "Luberon",
        "Lussac-Saint-Emilion",
        "L'Etoile",
        "Mâcon",
        "Macvin du Jura",
        "Madiran",
        "Malepère",
        "Maranges",
        "Marcillac",
        "Margaux",
        "Marsannay",
        "Maures",
        "Maury",
        "Mazis-Chambertin",
        "Mazoyères-Chambertin",
        "Méditerranée",
        "Médoc",
        "Menetou-Salon",
        "Mercurey",
        "Meursault",
        "Minervois",
        "Minervois-La Livinière",
        "Monbazillac",
        "Mont Caume",
        "Montagne-Saint-Emilion",
        "Montagny",
        "Monthélie",
        "Montlouis-sur-Loire",
        "Montrachet",
        "Montravel",
        "Morey-Saint-Denis",
        "Morgon",
        "Moselle",
        "Moulin-à-Vent",
        "Moulis",
        "Muscadet",
        "Muscadet Coteaux de la Loire",
        "Muscadet Côtes de Grandlieu",
        "Muscadet Sèvre et Maine",
        "Muscat de Beaumes-de-Venise",
        "Muscat de Frontignan",
        "Muscat de Lunel",
        "Muscat de Mireval",
        "Muscat de Rivesaltes",
        "Muscat de Saint-Jean-de-Minervois",
        "Muscat du Cap Corse",
        "Musigny",
        "Nuits-Saint-Georges",
        "Orléans",
        "Orléans-Cléry",
        "Pacherenc du Vic-Bilh",
        "Palette",
        "Patrimonio",
        "Pauillac",
        "Pays d'Hérault",
        "Pays d'Oc",
        "Pécharmant",
        "Périgord",
        "Pernand-Vergelesses",
        "Pessac-Léognan",
        "Petit Chablis",
        "Pierrevert",
        "Pineau des Charentes",
        "Pomerol",
        "Pommard",
        "Pouilly-Fuissé",
        "Pouilly-Fumé",
        "Pouilly-Loché",
        "Pouilly-sur-Loire",
        "Pouilly-Vinzelles",
        "Premières Côtes de Bordeaux",
        "Puisseguin-Saint-Emilion",
        "Puligny-Montrachet",
        "Puy-de-Dôme",
        "Quarts de Chaume",
        "Quincy",
        "Rasteau",
        "Régnié",
        "Reuilly",
        "Richebourg",
        "Rivesaltes",
        "Romanée-Conti",
        "Romanée-Saint-Vivant",
        "Rosé de Loire",
        "Rosé des Riceys",
        "Rosé d'Anjou",
        "Rosette",
        "Roussette de Savoie",
        "Roussette du Bugey",
        "Ruchottes-Chambertin",
        "Rully",
        "Sable de Camargue",
        "Saint-Amour",
        "Saint-Aubin",
        "Saint-Bris",
        "Saint-Chinian",
        "Saint-Emilion",
        "Saint-Emilion grand cru",
        "Saint-Estèphe",
        "Saint-Georges-Saint-Emilion",
        "Saint-Guilhem-le-Désert",
        "Saint-Joseph",
        "Saint-Julien",
        "Saint-Mont",
        "Saint-Nicolas-de-Bourgueil",
        "Saint-Péray",
        "Saint-Pourçain",
        "Saint-Romain",
        "Saint-Sardos",
        "Saint-Véran",
        "Sainte-Croix-du-Mont",
        "Sainte-Foy-Bordeaux",
        "Sainte-Marie-la-Blanche",
        "Sancerre",
        "Santenay",
        "Saône-et-Loire",
        "Saumur",
        "Saumur-Champigny",
        "Saussignac",
        "Sauternes",
        "Savennières",
        "Savigny-lès-Beaune",
        "Seyssel",
        "Tavel",
        "Thézac-Perricard",
        "Touraine",
        "Touraine Noble Joué",
        "Tursan",
        "Urfé",
        "Vacqueyras",
        "Val de Loire",
        "Valençay",
        "Vallée du Paradis",
        "Vallée du Torgan",
        "Var",
        "Vaucluse",
        "Ventoux",
        "Vicomté d'Aumelas",
        "Vin de Corse",
        "Vin de Savoie",
        "Vin des Allobroges",
        "Vins de la Corrèze",
        "Vinsobres",
        "Viré-Clessé",
        "Volnay",
        "Vosne-Romanée",
        "Vougeot",
        "Vouvray",
        "Yonne",
        "Vin d'Alsace",
        "Vin de Bellet",
        "Clos Vougeot",
        "Bourgogne grand ordinaire",
        "Bourgogne ordinaire",
        "Crozes-Ermitage",
        "Ermitage",
        "l'Hermitage",
        "l'Ermitage",
        "Moulis-en-Médoc",
        "Frontignan",
        "Vin de Frontignan",
        "Pineau Charentais",
        "Blanc Fumé de Pouilly",
        "Corse",
        "Savoie",
        "Côtes du Brian",
        "Neac",
        "Vin de France",
        "Vin de Table",
        "Santenay 1er cru",
        "Chablis 1er cru",
        "Beaune 1er cru",
        "Blagny 1er cru",
        "Auxey-Duresses 1er cru",
        "Aloxe-Corton 1er cru",
        "Maranges 1er cru",
        "Mercurey 1er cru",
        "Meursault 1er cru",
        "Montagny 1er cru",
        "Monthélie 1er cru",
        "Morey-Saint-Denis 1er cru",
        "Nuits-Saint-Georges 1er cru",
        "Pernand-Vergelesses 1er cru",
        "Pommard 1er cru",
        "Volnay 1er cru",
        "Puligny-Montrachet 1er cru",
        "Rully 1er cru",
        "Saint-Aubin 1er cru",
        "Savigny-lès-Beaune 1er cru",
        "Vosne-Romanée 1er cru",
        "Vougeot 1er cru",
        "Chambolle-Musigny 1er cru",
        "Chassagne-Montrachet 1er cru",
        "Fixin 1er cru",
        "Gevrey-Chambertin 1er cru",
        "Givry 1er cru",
        "Ladoix 1er cru",
        "Mâcon-Pierreclos",
        "Terre de Camargue",
        "Maury sec",
        "Saumur-Puy-Notre-Dame",
        "Blaye Côtes de Bordeaux",
        "Coteaux de Béziers",
        "Mont Baudile",
        "Champagne Grand Cru",
        "Saint-Guilhem-le-Désert Cité d'Aniane",
        "Saint-Guilhem-le-Désert Val de Montferrand",
        "Coteaux du Languedoc",
        "Picpoul de Pinet"
      ],
      winemakers: [
        "Domaine Olivier",
        "La Tour Saint Martin",
        "Château Tourril",
        "Domaine Coteaux Des Margots",
        "Domaine De Colonat",
        "Chateau La Mouline",
        "Roger & Christophe Moreux",
        "Domaine La Maurine",
        "Champagne Piot-Sévillano",
        "Domaine B Girardin",
        "Champagne Serveaux Fils",
        "Domaine De Pierre Belle",
        "Château Granins Grand Poujeaux",
        "Domaine Naïs",
        "Chateau La Gorre",
        "Château Haute-Nauve",
        "Jean-François Mérieau",
        "Domaine De Viaud",
        "Chateau Duplessy",
        "Domaine De Viaud",
        "Domaine Michelas",
        "Domaine Des Chailloux",
        "Domaine De Merlançon",
        "Domaine Du Champ Chapron",
        "Domaine Du Moulin De L'Horizon",
        "Domaine Des Hauts De Sanziers",
        "Château La Borie",
        "Champagne Biard-Loyaux",
        "Champagne G.Doré",
        "Vignobles Lafaye Pere Et Fils",
        "Chateau De Bonhoste",
        "Domaine Des Gravennes",
        "Champagne Du Rédempteur",
        "Domaine Rozel",
        "Domaine Louis Clerc",
        "Château La Prioulette",
        "Château Lafargue",
        "Domaine Du Mas De Rey",
        "Vignobles Bernard Reglat",
        "Vignobles Chaigne Et Fils",
        "Domaine Sauvete",
        "Château Trapaud",
        "Domaine Du Petit Barbaras",
        "Domaine Des Entrefaux",
        "Château Singleyrac",
        "Château Bel-Air",
        "Domaine Alban Roblin",
        "Chateau Haut Mousseau",
        "Château Les Tuileries",
        "Château La Grave Figeac",
        "Domaine Pierre Chauvin",
        "Domaine De Montine",
        "Château Ferry Lacombe",
        "Domaine Mazilly Pere &Fils",
        "Domaine Nudant Jean René",
        "Vignobles Garzaro",
        "Domaine De L'Epineau",
        "Château Henri Bonnaud",
        "Domaine Mesliand",
        "Domaine Dujardin",
        "Château De Cancerilles",
        "Domaine Du Clos D'Alari",
        "Domaine De La Portanière",
        "Chateau De Vauclaire",
        "Domaine Tabordet",
        "Château De La Croix",
        "Domaine Felix",
        "Chateau Haut Peyrillat",
        "Villa Minna Vineyard",
        "Château Brulesécaille",
        "Domaines De Fonscolombe",
        "Champagne Christian Naude",
        "La Mechiniere",
        "Domaine Belleville",
        "Domaine Du Colombier",
        "Domaine De La Guicharde",
        "Domaine L'Or De Line",
        "Mas De Boislauzon",
        "Domaine Saint Michel",
        "Domaine Petitjean",
        "Domaine Fourrey",
        "Les 3 Cellier",
        "Domaine Nebout",
        "Domaine Les Peyrieres",
        "Domaine De Magord",
        "Domaine Alain Mathias",
        "Domaine Les Terres D'Ocre",
        "Mas De La Baraque",
        "Scea Clos Des Américains",
        "Champagne Bonnevie Bocart",
        "Château De Sau",
        "Domaine Du Moulin De Descattes",
        "Domaine Des Couderousses",
        "Domaine Camp-Galhan",
        "Château De La Gardine",
        "Domaine Du Parc Saint Charles",
        "Vieux Manoir Du Frigoulas",
        "Domaine Bastide Jourdan",
        "Château D'Or Et De Gueules",
        "Le Mas Des Flauzieres",
        "Chateau Vessiere",
        "Chateau De Gourdon",
        "Chateau Terre Forte",
        "Domaine Du Dragon",
        "Domaine De L'Obrieu",
        "Domaine Manzone",
        "Domaine Carle Courty",
        "Domaine De Beaurenard",
        "Chateau Pesquie",
        "Château Thuron",
        "Domaine La Milliere",
        "Mas Peyre",
        "Domaine De L'Amauve",
        "Le Claux Delorme",
        "Domaine Du Clos De L Epinay",
        "Domaine Ferrer Ribière",
        "Domaine  Jas D'Esclans",
        "Domaine Mathieu",
        "Domaine Du Mas Alart",
        "Domaine Du Vistre",
        "Château De Clapier",
        "Champagne Castelger",
        "Domaine Riere Cadene",
        "Domaine Du Chanoine Rambert",
        "Château Lacapelle Cabanac",
        "Domaine Cathare",
        "Domaine De Prenant",
        "Domaine Ray",
        "Chateau Mont-Redon",
        "Champagne Yves Couvreur",
        "Château Pont De Brion",
        "Chateau Saint-Sauveur",
        "Chateau De Gaudou",
        "Domaine Vaquer",
        "Champagne Bression Sebastien",
        "Domaine De Magnaut",
        "Domaine Jean Georges Et Fils",
        "Domaine Sangouard-Guyot",
        "Domaine Des Fourquières",
        "Domaine Benoit Trichard",
        "Domaine De La Plaigne",
        "Château De Bertin",
        "Château Terre Vieille",
        "Domaine Passot Les Rampaux",
        "Domaine Sophie Cinier",
        "Domaine Saint-Laurent.   Sinard & Fils.",
        "Jean-Guillaume Passot",
        "Château Saint Louis",
        "Domaine De Castel Oualou",
        "Domaine Du Sancillon",
        "Domaine De La Grange Menard",
        "Domaine De L'Herbe Sainte",
        "Chateau De Javernand",
        "Domaine De L'Harmas",
        "Domaine Lagneau",
        "Esquisse - Domaine De Peyris",
        "Moelleux - Domaine De Peyris",
        "Rouge Fût - Domaine De Peyris",
        "Esprit De Domaine De Peyris - Blanc Sec",
        "Domaine Armand Gilg",
        "Chateau De Belle Isle",
        "Vins Spitz Et Fils",
        "Domaine Christophe Bleesz",
        "Chateau Famaey",
        "Domaine De Bacarra",
        "Vignobles Thevenet Et Fils",
        "Domaine Des Favards",
        "Domaine Du Merle",
        "Terres De Drollas",
        "Domaine Léon Heitzmann",
        "Domaine Les Cascades",
        "Domaine De La Gabilliere",
        "Chateau Les Palais",
        "Champagne Joseph Loriot Pagel",
        "Domaine Muller-Koeberle",
        "Paul Fahrer",
        "Domaine De Sancet",
        "Domaine Des Sept Vignes",
        "Domaine Monastrel",
        "Vins Bruno Hertz",
        "Domaine Philippe Schaeffer",
        "Michel Issaly",
        "Vins Wassler Jean Marie Et Fabrice",
        "Vignobles David",
        "Château De Pizay",
        "Domaine Lathuiliere-Gravallon",
        "Les Terres De Saint Hilaire",
        "Domaine Du Somail",
        "Chateau De Saint-Lager",
        "Domaine De Longueroche",
        "Champagne Benoît Cocteaux",
        "Domaine Des Persenades",
        "Château La Robertie",
        "Domaine Rigot",
        "Domaine Les Lutinieres",
        "Château De Chasselas",
        "Domaine Laguille",
        "Domaine Talmard Gerald",
        "Famille Laurent",
        "Ialach",
        "Château Paradis (Le Luc En Provence)",
        "Domaine Ologaray",
        "Domaine Joncy",
        "Tour De Belfort",
        "Beck Francis Et Fils",
        "Domaine De La Chapelle",
        "Domaine Sol-Payré",
        "Château Saint-Jacques D'Albas",
        "Jean Siegler - Clos Des Terres Brunes",
        "Chateau Guillem De Montjustin",
        "Bertrand Henry   Vigneron",
        "Chateau De L Herbe Sainte",
        "Domaine De Toasc",
        "Domaine De Rombeau",
        "Domaine Annie Sauvat",
        "Château Lestage-Darquier",
        "Domaine De Roc Fontaine",
        "Domaine Du Dernier Bastion",
        "Domaine Du Barvy",
        "Chateau De Bertin",
        "Chateau De Bertin",
        "Domaine De La Mayonnette",
        "Château Saint Esteve D'Uchaux",
        "Vins D'Alsace Robert Blanck",
        "Domaine Gabriel Bouchard",
        "Domaine De Cézin",
        "Domaine Du Rochouard",
        "Clos De Venes",
        "Chateau Cambriel",
        "Cave Bonvin - Domaine De La Sourde",
        "Domaine De La Rouletière",
        "Domaine De Lagoy",
        "Château Crémade",
        "Domaine Saint Siffrein",
        "Domaine Clair Moreau",
        "Domaine De L'Oriel",
        "Chateau De Fontlade",
        "Château De L'Ou",
        "Château De La Viaudière",
        "Domaine Des Sauvaire - Reilhe",
        "Château Yon St Christophe",
        "Blanc De Brulesécaille",
        "Château La Gravière",
        "Domaine De La Rencontre",
        "Château Vieux Mougnac",
        "Les Vins De Christine Nadalie",
        "Domaine Cambriel",
        "Château Pontac Gadet",
        "Optimus Le Grand Vin Du Château Pontac Gadet",
        "Domaine Philippe Et Vincent Jaboulet",
        "Domaine De Guillon",
        "Terres De Roa",
        "Alain Faget",
        "Villa Delort",
        "Richard Réthoré",
        "Domaine De Tempere",
        "Domaine Boisson",
        "Domaine Des Homs",
        "Domaine Hubert Metz",
        "Chateau Pech Rosie",
        "Château De Vaucouleurs",
        "Mas Baladerne",
        "Domaine Des Conquêtes",
        "Domaine Vordy",
        "Domaine Bonian",
        "Domaine Capitelle Des Salles",
        "Champagne Bouquet",
        "Domaine De La Rochelierre",
        "Champagne Mary Sessile",
        "Champagne Xavier Loriot",
        "Château Dubraud",
        "Domaine Habrard",
        "Mas De Bayle",
        "Domaine Ansen",
        "Domaine Salmon",
        "Champagne Pascal Henin",
        "Domaine De Gravanel",
        "Champagne André Tixier & Fils",
        "Mas De L'Erme",
        "Allegria",
        "Maison Angelot",
        "Domaine Massillan",
        "Champagne Colin",
        "Domaine De La Conseillère",
        "Champagne Le Gallais",
        "Domaine Robert Klingenfus",
        "Domaine Du Closel",
        "Domaine Saint Marc",
        "Domaine Lucien Tramier",
        "Domaine De Malaïgue",
        "Chateau De Raissac",
        "Domaine La Maurerie",
        "Château Du Carruge",
        "Domaine Peut-Être",
        "Mas D'Isnard",
        "Domaine Plessis Glain",
        "Domaine Les 3 Ecus",
        "Château Cap De Fouste",
        "Domaine Eric Gelly",
        "Domaine Roubaud",
        "Château Du Barry",
        "Chateau Mignan",
        "Extrait De Rambaud",
        "Domaine Le Portail",
        "Château Rambaud",
        "Nouvelle Terre",
        "Champagne Jean Josselin",
        "Champagne Philippe Doury",
        "Domaine Reine Juliette",
        "Domaine Saint Michel Archange",
        "Abbaye De Fontfroide",
        "Domaine Chesneau & Fils",
        "Domaine Sylvie Fahrer Et Fils",
        "Mas Des Manhans",
        "Domaine De Champal",
        "Domaine Les Quatre Amours",
        "Domaine Des Prés Lasses",
        "Domaine Rety",
        "Domaine Grand Saint-Cyr",
        "Vins Geiger Koenig",
        "Clos Ventas",
        "Domaine De La Valière",
        "Villa Tempora",
        "Domaine Olivier",
        "Château Haut Blanville",
        "Domaine Clamouse",
        "Mas René Guilhem",
        "Clos Des Augustins",
        "Le Clos D'Orlea",
        "Domaine De Ravanès",
        "Domaine Du Vieux Chai",
        "Champagne Proy Goulard",
        "Domaine De La Rouquette",
        "Domaine Des Pradels Quartironi",
        "Domaine La Tour Penedesses",
        "Les Vallons De Fontfresque",
        "Domaine Jean-Paul Champagnon",
        "Château Thuerry",
        "Domaine Hamet-Spay",
        "Domaine De L'Estello",
        "Château Barbeiranne",
        "Chateau De Flaugergues",
        "Domaine Moltès",
        "Joseph Gsell",
        "Domaine Blard",
        "Domaine Pierre Rougon",
        "Domaine Monplezy",
        "Domaine Berrod",
        "Château De Stony",
        "Domaine De La Coste",
        "Domaine De La Tour",
        "Domaine Saint Pierre Des Bois",
        "Champagne Aspasie",
        "Domaine Champs Blancs",
        "Joly Champagne",
        "Domaine Castan",
        "Château Pipeau",
        "Château Joinin",
        "Domaine Du Joncas",
        "Domaine Du Fondis",
        "Domaine La Roche Moreau",
        "Domaine Les Trois Puechs",
        "Domaine De La Tour",
        "Le Mas De Sipière",
        "Domaine De Mallemort",
        "Domaine De Bannières",
        "Domaine Grasset Rives",
        "Château De Pinet",
        "Domaine Gaujal De Saint Bon",
        "Domaine Maspiquet",
        "Domaine Les Grandes Costes",
        "Château La Rose Sarron",
        "Domaine Collet",
        "Domaine De Lanzac",
        "Mas Canaille",
        "Domaine Ligier",
        "Domaine Le Fesq",
        "Château Maison Noble St Martin",
        "Domaine Du Vieux Pressoir",
        "Domaine Jacques Faure - Luc Faure Vigneron",
        "Le Plan De L'Homme",
        "Château De L'Oiselinière",
        "Domaine De Chantemerle",
        "Chateau Du Cros",
        "Domaine De Monterrain",
        "Chateau Haut Mayne",
        "Domaine De La Chapinière",
        "Domaine De L'Estan",
        "Domaine De Larzac",
        "Domaine De La Ronze",
        "Domaine Les Pins",
        "Domaine Marié",
        "Domaine Du Revaou",
        "Champagne Marc",
        "Chateau De Coudot",
        "Domaine Pain Du Sucre",
        "Domaine De La Grange",
        "Domaine Du Mas Rouge",
        "Domaine De Mingraut",
        "Domaine De Perdiguier",
        "Domaine Grand Romane",
        "Domaine Corsin",
        "Chateau Soucherie",
        "Château De Sauvage",
        "Domaine Du Fraïsse",
        "Domaine J Boulon",
        "Christophe Savoye",
        "Domaine De La Raimbaudière",
        "Chateau Caillou",
        "Domaine Du Mas De La Doux",
        "Château Castel La Rose",
        "Domaine La Grangette",
        "Chateau Les Bertrands",
        "Domaine La Haute Févrie",
        "Domaine  La Femme Allongée",
        "Domaine Le Pech D'André",
        "Chateau La Vaisinerie",
        "Domaine La Guillaumerie",
        "Domaine Le Mirabeau",
        "Château Du Grand Barrail",
        "Château De Brague",
        "Christian Et Fabien Tessier - Domaine De La Désoucherie",
        "Domaine De Puilacher",
        "Domaine Les Fenals",
        "Chateau De Belleverne",
        "Château Peybrun",
        "Domaine Des Fonds",
        "Domaine Serge Dagueneau Et Filles",
        "Château Les Amoureuses",
        "Chateau La Croix Meunier",
        "Domaine Caslot Bourdin",
        "Château Saint Roch",
        "Domaine Berthet-Bondet",
        "Domaine Pierre Et Bertrand Couly",
        "Domaine André Berthet-Rayne",
        "Chateau La Valade",
        "Chateau Langoiran",
        "Domaine Champ-Long",
        "Château Saint-Esprit",
        "Domaine La Garrigue",
        "Chateau Bourseau",
        "Le Cellier Du Palais",
        "Domaine Guerrin Gilles",
        "Champagne Vincent Lamoureux",
        "Domaine De La Denante",
        "Chateau La Tour De By",
        "Château De Chaintres",
        "Domaine De Villemont",
        "Domaine De La Combe Au Loup",
        "Chateau Canon La Valade",
        "Chateau De Cabran",
        "Vignobles Albert Yung",
        "Domaine La Fourmone",
        "Domaine Edmond Rentz",
        "Chateaux Cailley",
        "Domaine De L'Olivette",
        "Clos Sorian",
        "Chateau Lamothe Vincent",
        "Domaine L Ancienne Cure",
        "Domaine Clos De L'Ours",
        "Domaine Olivier Hillaire",
        "Domaine Lanye-Barrac",
        "Chateau De Lascours",
        "Domaine André Rampon",
        "Champagne Mousse Galoteau Et Fils",
        "Domaine François Charpentier Et Fils",
        "Domaine Croix-Rousse",
        "Champagne Veuve Godart & Fils",
        "Domaine Virely-Rougeot",
        "Chateaux Pomys Et Saint-Estephe",
        "Domaine A Ronca",
        "Domaine Capendu"
        ]
    };
  }
})();