(function () {
  'use strict';

  angular
      .module('vinibar.winemaker.characteristics', [])
      .factory('WineCharacteristicsFactory', WineCharacteristicsFactory);

  /* @ngInject */
  function WineCharacteristicsFactory () {
    return {
      varieties: [
        "ABONDANT",
        "ABOURIOU (GAMAY SAINT-LAURENT)",
        "ABOURIOU",
        "ALEATICO",
        "ALICANTE BOUSCHET",
        "ALIGOTÉ",
        "ALPHONSE LAVALLÉE",
        "ALTESSE",
        "ALVARINHO",
        "ALÉATICO",
        "ARAGNAN",
        "ARAMON BLANC",
        "ARAMON GRIS",
        "ARAMON",
        "ARANEL",
        "ARBANE",
        "ARGENTÉ",
        "ARINARNOA",
        "ARRILOBA",
        "ARROUYA",
        "ARRUFIAC",
        "ARVINE",
        "AUBIN VERT",
        "AUBIN",
        "AUBUN",
        "AUXERROIS",
        "BACHET",
        "BACO BLANC",
        "BARBAROUX",
        "BAROQUE",
        "BIANCU GENTILE",
        "BLANC DAME",
        "BLANC",
        "BLANQUEIRON",
        "BOUCHALÈS",
        "BOUILLET",
        "BOUQUETTRAUBE",
        "BOURBOULENC",
        "BOUTEILLAN",
        "BRACHET",
        "BRAQUET",
        "BRUN ARGENTÉ",
        "BRUN FOURCA",
        "BRUN",
        "BÉCLAN",
        "BÉQUIGNOL",
        "CABERNET FRANC",
        "CABERNET SAUVIGNON",
        "CABERNET",
        "CALADOC",
        "CALITOR",
        "CAMARALET DE LASSEUBE",
        "CARCAJOLO BLANC",
        "CARCAJOLO",
        "CARDINAL",
        "CARIGNAN BLANC",
        "CARIGNAN",
        "CARMÉNÈRE",
        "CASTETS",
        "CHAMBOURCIN",
        "CHARDONNAY",
        "CHARSAN",
        "CHASAN",
        "CHASSELAS ROSE",
        "CHASSELAS ROSÉ",
        "CHASSELAS",
        "CHATUS",
        "CHENANSON NOIR",
        "CHENANSON",
        "CHENIN",
        "CINSAULT",
        "CINSAUT",
        "CLAIRETTE ROSE",
        "CLAIRETTE",
        "CLARIN",
        "CLAVERIE",
        "CODIVARTA",
        "COLOBEL",
        "COLOMBARD",
        "COLOMBAUD",
        "CORBEAU",
        "COT",
        "COUDERC NOIR",
        "COUDERC",
        "COUNOISE",
        "COURBU NOIR",
        "COURBU",
        "COUSTON",
        "CROUCHEN",
        "CÉSAR",
        "CÔT",
        "DANLAS",
        "DOUCILLON BLANC",
        "DURAS",
        "DURIF",
        "EGIODOLA",
        "EKIGAÏNA",
        "ELBLING",
        "ETRAIRE DE LA DUI",
        "FER SERVADOU",
        "FER",
        "FERRAUDOU",
        "FEUNATE",
        "FLORENTAL",
        "FOLIGNAN",
        "FOLLE BLANCHE",
        "FOURCA",
        "FRANC NOIR DE HAUTE-SAÔNE",
        "FRÉAUX",
        "FUELLA NERA",
        "FURMINT",
        "GAMARET",
        "GAMAY DE BOUZE",
        "GAMAY DE CHAUDENAY",
        "GAMAY FRÉAUX",
        "GAMAY NOIR À JUS BLANC",
        "GAMAY NOIR",
        "GAMAY",
        "GANSON",
        "GARONNET",
        "GASCON",
        "GENOVÈSE",
        "GENTILE",
        "GEWURZTRAMINER",
        "GOLDRIESLING",
        "GOUGET",
        "GRAINS",
        "GRAISSE",
        "GRAMON",
        "GRASSEN",
        "GRENACHE BLANC",
        "GRENACHE GRIS",
        "GRENACHE NOIR",
        "GRENACHE ROUGE",
        "GRENACHE",
        "GRINGET",
        "GROLLEAU GRIS",
        "GROLLEAU",
        "GROS MANSENG",
        "GROS VERT",
        "JACQUÈRE",
        "JOUBERTIN",
        "JURANÇON BLANC",
        "JURANÇON NOIR",
        "KNIPPERLÉ",
        "LANDAL",
        "LAUZET",
        "LEN DE L'EL",
        "LILIORILA",
        "LISTAN",
        "LIVAL",
        "LLEDONER PELUT",
        "LLEDONER PELUT",
        "LLEDONNER PELUT",
        "LÉON MILLOT",
        "MACABEU",
        "MALBEC",
        "MANCIN",
        "MANOSQUIN",
        "MANSENG NOIR",
        "MANSENG",
        "MARSANNE",
        "MARSELAN",
        "MARÉCHAL FOCH ",
        "MARÉCHAL FOCH",
        "MAUZAC BLANC",
        "MAUZAC ROSE",
        "MAUZAC ROSÉ",
        "MAUZAC",
        "MAYORQUIN",
        "MECLE",
        "MELON",
        "MERILLE",
        "MERLOT BLANC",
        "MERLOT NOIR",
        "MERLOT",
        "MESLIER SAINT-FRANÇOIS",
        "MILGRANET",
        "MOLETTE",
        "MOLLARD",
        "MONCADE",
        "MONDEUSE BLANCHE",
        "MONDEUSE",
        "MONERAC",
        "MONTILS",
        "MORNEN",
        "MORRASTEL (MINUSTELLO)",
        "MORRASTEL",
        "MOURVAISON",
        "MOURVÈDRE",
        "MOUYSSAGUÈS",
        "MURESCONU",
        "MUSCADELLE",
        "MUSCADIN",
        "MUSCARDIN",
        "MUSCAT CENDRÉ",
        "MUSCAT D'ALEXANDRIE",
        "MUSCAT DE HAMBOURG",
        "MUSCAT OTTONEL",
        "MUSCAT PETITS GRAINS",
        "MUSCAT À PETITS GRAINS BLANCS",
        "MUSCAT À PETITS GRAINS COTEAUX DE L'AINS",
        "MUSCAT À PETITS GRAINS ROSÉS",
        "MUSCAT À PETITS GRAINS ROUGES",
        "MUSCAT À PETITS GRAINS",
        "MUSCAT À PETITS GRAINS",
        "MÈCLE",
        "MÉRILLE",
        "MÜLLER-THURGAU",
        "NIELLUCIO",
        "NOIR FLEURIEN",
        "NÉGRET DE BANHARS",
        "NÉGRETTE",
        "OBERLIN",
        "ONDENC",
        "ORBOIS",
        "PAGADEBITI",
        "PANSE MUSCADE (OU PANSE DU ROY RENÉ)",
        "PARELLADA",
        "PASCAL",
        "PERDEA",
        "PERSAN",
        "PETIT BRUN",
        "PETIT COURBU",
        "PETIT MANSENG",
        "PETIT MESLIER",
        "PETIT VERDOT N",
        "PETIT VERDOT",
        "PICARDAN",
        "PINEAU D'AUNIS",
        "PINEAU DE LA LOIRE",
        "PINOT BLANC",
        "PINOT GRIS",
        "PINOT MEUNIER",
        "PINOT NOIR VINIFÉ EN BLANC",
        "PINOT NOIR",
        "PINOT",
        "PIQUEPOUL BLANC",
        "PIQUEPOUL GRIS",
        "PIQUEPOUL NOIR",
        "PIQUEPOUL",
        "PLANT DE BRUNEL",
        "PLANT DROIT",
        "PLANTET",
        "PORTAN",
        "PORTUGAIS BLEU",
        "POULSARD",
        "PRUNELARD",
        "PRÉCOCE BOUSQUET",
        "PRÉCOCE DE MALINGRE",
        "RAFFIAT DE MONCADE",
        "RAVAT BLANC",
        "RAYON D'OR",
        "RIBOL",
        "RIESLING",
        "RIMINÈSE",
        "RIVAIRENC BLANC",
        "RIVAIRENC GRIS",
        "RIVAIRENC",
        "ROLLE",
        "ROMORANTIN",
        "ROSÉ DU VAR",
        "ROUBLOT",
        "ROUSSANNE",
        "ROUSSETTE D'AYZE",
        "RUBILANDE",
        "SACY",
        "SAINT-CÔME",
        "SAINT-MACAIRE",
        "SAINT-PIERRE DORÉ",
        "SAUVIGNON BLANC",
        "SAUVIGNON GRIS",
        "SAUVIGNON",
        "SAVAGNIN BLANC",
        "SAVAGNIN ROSE",
        "SAVAGNIN ROSÉ (TRAMINER)",
        "SAVAGNIN",
        "SCIACCARELLO",
        "SEINOIR",
        "SELECT",
        "SERVANIN",
        "SERVANT",
        "SEYVAL",
        "SYLVANER",
        "SYRAH",
        "SÉGALIN",
        "SÉMILLON",
        "SÉMÉBAT",
        "TANANT",
        "TANNAT",
        "TEMPRANILLO",
        "TERRET BLANC",
        "TERRET GRIS",
        "TERRET NOIR",
        "TIBOUREN",
        "TOURBAT (OU MALVOISIE DU ROUSSILLON)",
        "TOURBAT",
        "TRESSALIER",
        "TRESSOT",
        "TROUSSEAU",
        "TÉOULIER",
        "UGNI BLANC (ROUSSAN)",
        "UGNI BLANC",
        "UGNI ROSÉ",
        "UGNI ROSÉ",
        "VALDIGUIÉ",
        "VALDIQUIÉ",
        "VALÉRIEN",
        "VAROUSSET",
        "VELTELINER ROUGE PRÉCOCE",
        "VERDELHO",
        "VERDESSE",
        "VERDOT",
        "VERMENTINO OU ROLLE",
        "VILLARD BLANC",
        "VILLARD NOIR",
        "VILLARD",
        "VIOGNIER"
      ]
    };
  }
})();